name: Preview

on: pull_request

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: DNSControl preview
        uses: speedmann/dnscontrol-action@main
        id: dnscontrol_preview
        env:
          HOSTING_TOKEN: ${{ secrets.HOSTING_TOKEN }}
          INWX_USER: ${{ secrets.INWX_USER }}
          INWX_PASSWORD: ${{ secrets.INWX_PASSWORD }}

        with:
          args: preview

          # Optionally, if your DNSConfig files are in a non-default location,
          # you could specify the paths to the config and credentials file.
          config_file: 'dnsconfig.js'
          creds_file: 'github_creds.json'
      - name: Preview pull request comment
        uses: unsplash/comment-on-pr@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            ```
            ${{ steps.dnscontrol_preview.outputs.output }}
            ```
         check_for_duplicate_msg: true
